### PR TITLE
Support tag in mutation query builder

### PR DESCRIPTION
**Pull request by dcilke**
Adds support for tagging mutation api calls via a `tag` query parameter.

### CODE REVIEW

**Comment by atombender** [comment]
Should this not be generalized for all types of API requests? I think I'd prefer something like:

```go
client := New("myproject", WithTag("sanity.stuff"))
client.Mutate(...)
```

We also allow getting a new client with new options, so that you just do it for a single request:

```
client.WithOptions(WithTag("sanity.stuff")).Mutate(...)
```

**Comment by dcilke** [comment]
We can implement that option, however, we often tag per request type (get documents vs mutations).

**Comment by atombender** [comment]
How is that not addressed by my second code example?

**Comment by dcilke** [comment]
Doesn't it make it more difficult to have a reusable client and per request tagging? i.e.
```
client.Mutation(...).Tag('mutate')
...
client.Query(...).Tag('query')
```

**Comment by atombender** [comment]
How is that different from (other than verbosity, and we could have a `client.Tag()` method as a shortcut):

```go
client.WithOptions(WithTag("mutate")).Mutation(...)
...
client.WithOptions(WithTag("query")).Query(...)
```

**Comment by dcilke** [comment]
Would `WithOptions` return a deep clone of the client? I would think you would run into the issue of
```go
client.WithOptions(WithTag("mutate")).Mutation(...)
...
client.Query(...) // wrongly tagged with "mutate"
```

**Comment by atombender** [comment]
Yes, it clones the client.

**Comment by dcilke** [comment]
Maybe this is going in the wrong direction, but I've updated this PR to allow the client to specify a default tag, which each builder allows the tag to be overwritten. @atombender wdyt?

**Review by atombender — APPROVED** [review]
That works.

**Pull request merged**
